"""empty message

Revision ID: 904d1921c9fb
Revises: a24399da66ad
Create Date: 2018-03-04 19:15:36.964614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904d1921c9fb'
down_revision = 'a24399da66ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
